"""create_initial_analyzer_schema

Revision ID: a9431de6a932
Revises:
Create Date: 2026-09-27 18:41:39.574477

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "a9431de6a932"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_subject", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_event")),
    )
    op.create_index(op.f("ix_audit_event_action"), "audit_event", ["action"], unique=False)
    op.create_table(
        "benchmark_metric_definition",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("metric_key", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("subsystem", sa.String(length=32), nullable=False),
        sa.Column("unit", sa.String(length=64), nullable=False),
        sa.Column("direction", sa.String(length=32), nullable=False),
        sa.Column("min_sample_count", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "direction IN ('higher_is_better', 'lower_is_better')",
            name=op.f("ck_benchmark_metric_definition_valid_metric_direction"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_benchmark_metric_definition")),
    )
    op.create_index(
        op.f("ix_benchmark_metric_definition_metric_key"),
        "benchmark_metric_definition",
        ["metric_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_benchmark_metric_definition_subsystem"),
        "benchmark_metric_definition",
        ["subsystem"],
        unique=False,
    )
    op.create_table(
        "benchmark_source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("source_name", sa.String(length=128), nullable=False),
        sa.Column("benchmark_version", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.String(length=512), nullable=False),
        sa.Column("license_spdx", sa.String(length=64), nullable=False),
        sa.Column("license_notes", sa.Text(), nullable=True),
        sa.Column("is_approved", sa.Boolean(), nullable=False),
        sa.Column(
            "last_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_benchmark_source")),
        sa.UniqueConstraint("code", name=op.f("uq_benchmark_source_code")),
    )
    op.create_table(
        "hardware_component",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("component_type", sa.String(length=32), nullable=False),
        sa.Column("brand", sa.String(length=64), nullable=False),
        sa.Column("model_name", sa.String(length=160), nullable=False),
        sa.Column("generation", sa.String(length=64), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "component_type IN ('CPU', 'GPU', 'RAM', 'STORAGE')",
            name=op.f("ck_hardware_component_valid_component_type"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hardware_component")),
        sa.UniqueConstraint(
            "component_type", "brand", "model_name", name="uq_hardware_component_identity"
        ),
    )
    op.create_index(
        op.f("ix_hardware_component_brand"), "hardware_component", ["brand"], unique=False
    )
    op.create_index(
        op.f("ix_hardware_component_component_type"),
        "hardware_component",
        ["component_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hardware_component_model_name"), "hardware_component", ["model_name"], unique=False
    )
    op.create_table(
        "normalization_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version_code", sa.String(length=64), nullable=False),
        sa.Column("method", sa.String(length=64), nullable=False),
        sa.Column("formula_notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_normalization_version")),
        sa.UniqueConstraint("version_code", name=op.f("uq_normalization_version_version_code")),
    )
    op.create_table(
        "scoring_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version_code", sa.String(length=64), nullable=False),
        sa.Column("tier_thresholds_json", sa.JSON(), nullable=False),
        sa.Column("balance_thresholds_json", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scoring_version")),
        sa.UniqueConstraint("version_code", name=op.f("uq_scoring_version_version_code")),
    )
    op.create_table(
        "user_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("auth_subject", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_profile")),
    )
    op.create_index(
        op.f("ix_user_profile_auth_subject"), "user_profile", ["auth_subject"], unique=True
    )
    op.create_table(
        "workload_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workload_profile")),
        sa.UniqueConstraint("slug", "version", name="uq_workload_profile_slug_version"),
    )
    op.create_index(op.f("ix_workload_profile_slug"), "workload_profile", ["slug"], unique=False)
    op.create_table(
        "component_alias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("component_id", sa.Integer(), nullable=False),
        sa.Column("component_type", sa.String(length=32), nullable=False),
        sa.Column("alias_name", sa.String(length=255), nullable=False),
        sa.Column("source_name", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["hardware_component.id"],
            name=op.f("fk_component_alias_component_id_hardware_component"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_component_alias")),
        sa.UniqueConstraint("component_type", "alias_name", name="uq_component_alias_type_name"),
    )
    op.create_index(
        op.f("ix_component_alias_alias_name"), "component_alias", ["alias_name"], unique=False
    )
    op.create_index(
        op.f("ix_component_alias_component_id"), "component_alias", ["component_id"], unique=False
    )
    op.create_table(
        "component_specification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("component_id", sa.Integer(), nullable=False),
        sa.Column("core_count", sa.Integer(), nullable=True),
        sa.Column("thread_count", sa.Integer(), nullable=True),
        sa.Column("vram_gb", sa.Integer(), nullable=True),
        sa.Column("ram_capacity_gb", sa.Integer(), nullable=True),
        sa.Column("memory_speed", sa.String(length=64), nullable=True),
        sa.Column("storage_type", sa.String(length=64), nullable=True),
        sa.Column("specs_json", sa.JSON(), nullable=False),
        sa.Column("source_url", sa.String(length=512), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["hardware_component.id"],
            name=op.f("fk_component_specification_component_id_hardware_component"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_component_specification")),
        sa.UniqueConstraint("component_id", name=op.f("uq_component_specification_component_id")),
    )
    op.create_table(
        "normalized_metric",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("component_id", sa.Integer(), nullable=False),
        sa.Column("metric_definition_id", sa.Integer(), nullable=False),
        sa.Column("normalization_version_id", sa.Integer(), nullable=False),
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("raw_aggregated_score", sa.Float(), nullable=False),
        sa.Column("normalized_score_0_100", sa.Float(), nullable=False),
        sa.Column("percentile", sa.Float(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("confidence_contribution", sa.Float(), nullable=False),
        sa.Column(
            "calculated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "normalized_score_0_100 >= 0.0 AND normalized_score_0_100 <= 100.0",
            name=op.f("ck_normalized_metric_normalized_score_bounds"),
        ),
        sa.CheckConstraint(
            "percentile >= 0.0 AND percentile <= 100.0",
            name=op.f("ck_normalized_metric_percentile_bounds"),
        ),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["hardware_component.id"],
            name=op.f("fk_normalized_metric_component_id_hardware_component"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["metric_definition_id"],
            ["benchmark_metric_definition.id"],
            name=op.f("fk_normalized_metric_metric_definition_id_benchmark_metric_definition"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["normalization_version_id"],
            ["normalization_version.id"],
            name=op.f("fk_normalized_metric_normalization_version_id_normalization_version"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_normalized_metric")),
        sa.UniqueConstraint(
            "component_id",
            "metric_definition_id",
            "normalization_version_id",
            "dataset_version",
            name="uq_normalized_metric_versioned",
        ),
    )
    op.create_index(
        op.f("ix_normalized_metric_component_id"),
        "normalized_metric",
        ["component_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_normalized_metric_dataset_version"),
        "normalized_metric",
        ["dataset_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_normalized_metric_metric_definition_id"),
        "normalized_metric",
        ["metric_definition_id"],
        unique=False,
    )
    op.create_table(
        "pc_build",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("workload_profile_id", sa.Integer(), nullable=False),
        sa.Column("is_saved", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_profile.id"],
            name=op.f("fk_pc_build_user_id_user_profile"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workload_profile_id"],
            ["workload_profile.id"],
            name=op.f("fk_pc_build_workload_profile_id_workload_profile"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pc_build")),
    )
    op.create_index(op.f("ix_pc_build_user_id"), "pc_build", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_pc_build_workload_profile_id"), "pc_build", ["workload_profile_id"], unique=False
    )
    op.create_table(
        "raw_dataset_snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_uri", sa.String(length=512), nullable=False),
        sa.Column("manifest_json", sa.JSON(), nullable=False),
        sa.Column(
            "retrieved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["benchmark_source.id"],
            name=op.f("fk_raw_dataset_snapshot_source_id_benchmark_source"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_dataset_snapshot")),
        sa.UniqueConstraint("source_id", "dataset_version", name="uq_source_dataset_version"),
    )
    op.create_index(
        op.f("ix_raw_dataset_snapshot_dataset_version"),
        "raw_dataset_snapshot",
        ["dataset_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_dataset_snapshot_source_id"),
        "raw_dataset_snapshot",
        ["source_id"],
        unique=False,
    )
    op.create_table(
        "workload_weight",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workload_profile_id", sa.Integer(), nullable=False),
        sa.Column("metric_definition_id", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("minimum_adequacy_score", sa.Float(), nullable=True),
        sa.CheckConstraint(
            "weight > 0.0 AND weight <= 1.0", name=op.f("ck_workload_weight_valid_weight_range")
        ),
        sa.ForeignKeyConstraint(
            ["metric_definition_id"],
            ["benchmark_metric_definition.id"],
            name=op.f("fk_workload_weight_metric_definition_id_benchmark_metric_definition"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workload_profile_id"],
            ["workload_profile.id"],
            name=op.f("fk_workload_weight_workload_profile_id_workload_profile"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workload_weight")),
        sa.UniqueConstraint(
            "workload_profile_id", "metric_definition_id", name="uq_workload_metric_weight"
        ),
    )
    op.create_index(
        op.f("ix_workload_weight_workload_profile_id"),
        "workload_weight",
        ["workload_profile_id"],
        unique=False,
    )
    op.create_table(
        "analysis_result",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("share_uuid", sa.String(length=64), nullable=False),
        sa.Column("pc_build_id", sa.Integer(), nullable=False),
        sa.Column("workload_profile_id", sa.Integer(), nullable=False),
        sa.Column("scoring_version_id", sa.Integer(), nullable=False),
        sa.Column("normalization_version_id", sa.Integer(), nullable=False),
        sa.Column("dataset_version", sa.String(length=64), nullable=False),
        sa.Column("performance_score_0_100", sa.Float(), nullable=False),
        sa.Column("performance_tier", sa.String(length=32), nullable=False),
        sa.Column("balance_score_0_100", sa.Float(), nullable=False),
        sa.Column("balance_status", sa.String(length=64), nullable=False),
        sa.Column("confidence_score_0_100", sa.Float(), nullable=False),
        sa.Column("confidence_level", sa.String(length=32), nullable=False),
        sa.Column("warnings_json", sa.JSON(), nullable=False),
        sa.Column(
            "analyzed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "balance_score_0_100 >= 0.0 AND balance_score_0_100 <= 100.0",
            name=op.f("ck_analysis_result_analysis_balance_score_bounds"),
        ),
        sa.CheckConstraint(
            "confidence_score_0_100 >= 0.0 AND confidence_score_0_100 <= 100.0",
            name=op.f("ck_analysis_result_analysis_confidence_score_bounds"),
        ),
        sa.CheckConstraint(
            "performance_score_0_100 >= 0.0 AND performance_score_0_100 <= 100.0",
            name=op.f("ck_analysis_result_analysis_perf_score_bounds"),
        ),
        sa.ForeignKeyConstraint(
            ["normalization_version_id"],
            ["normalization_version.id"],
            name=op.f("fk_analysis_result_normalization_version_id_normalization_version"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pc_build_id"],
            ["pc_build.id"],
            name=op.f("fk_analysis_result_pc_build_id_pc_build"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scoring_version_id"],
            ["scoring_version.id"],
            name=op.f("fk_analysis_result_scoring_version_id_scoring_version"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workload_profile_id"],
            ["workload_profile.id"],
            name=op.f("fk_analysis_result_workload_profile_id_workload_profile"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_result")),
    )
    op.create_index(
        op.f("ix_analysis_result_dataset_version"),
        "analysis_result",
        ["dataset_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_result_pc_build_id"), "analysis_result", ["pc_build_id"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_result_share_uuid"), "analysis_result", ["share_uuid"], unique=True
    )
    op.create_table(
        "benchmark_observation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("component_id", sa.Integer(), nullable=True),
        sa.Column("metric_definition_id", sa.Integer(), nullable=False),
        sa.Column("reported_device_name", sa.String(length=255), nullable=False),
        sa.Column("benchmark_version", sa.String(length=64), nullable=False),
        sa.Column("raw_score", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=64), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("environment_json", sa.JSON(), nullable=False),
        sa.Column("is_quarantined", sa.Boolean(), nullable=False),
        sa.Column("tested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "imported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "raw_score > 0", name=op.f("ck_benchmark_observation_positive_raw_score")
        ),
        sa.CheckConstraint(
            "sample_count >= 1", name=op.f("ck_benchmark_observation_positive_sample_count")
        ),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["hardware_component.id"],
            name=op.f("fk_benchmark_observation_component_id_hardware_component"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["metric_definition_id"],
            ["benchmark_metric_definition.id"],
            name=op.f("fk_benchmark_observation_metric_definition_id_benchmark_metric_definition"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["raw_dataset_snapshot.id"],
            name=op.f("fk_benchmark_observation_snapshot_id_raw_dataset_snapshot"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["benchmark_source.id"],
            name=op.f("fk_benchmark_observation_source_id_benchmark_source"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_benchmark_observation")),
    )
    op.create_index(
        op.f("ix_benchmark_observation_component_id"),
        "benchmark_observation",
        ["component_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_benchmark_observation_snapshot_id"),
        "benchmark_observation",
        ["snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_benchmark_observation_source_id"),
        "benchmark_observation",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        "ix_observation_component_metric",
        "benchmark_observation",
        ["component_id", "metric_definition_id"],
        unique=False,
    )
    op.create_table(
        "ingestion_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("rows_processed", sa.Integer(), nullable=False),
        sa.Column("rows_inserted", sa.Integer(), nullable=False),
        sa.Column("rows_quarantined", sa.Integer(), nullable=False),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["raw_dataset_snapshot.id"],
            name=op.f("fk_ingestion_run_snapshot_id_raw_dataset_snapshot"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_run")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_ingestion_run_idempotency_key")),
    )
    op.create_index(
        op.f("ix_ingestion_run_snapshot_id"), "ingestion_run", ["snapshot_id"], unique=False
    )
    op.create_table(
        "pc_build_component",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pc_build_id", sa.Integer(), nullable=False),
        sa.Column("component_id", sa.Integer(), nullable=False),
        sa.Column("slot_type", sa.String(length=32), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "slot_type IN ('CPU', 'GPU', 'RAM', 'STORAGE')",
            name=op.f("ck_pc_build_component_valid_build_slot_type"),
        ),
        sa.CheckConstraint(
            "quantity >= 1", name=op.f("ck_pc_build_component_positive_build_component_quantity")
        ),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["hardware_component.id"],
            name=op.f("fk_pc_build_component_component_id_hardware_component"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pc_build_id"],
            ["pc_build.id"],
            name=op.f("fk_pc_build_component_pc_build_id_pc_build"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pc_build_component")),
    )
    op.create_index(
        op.f("ix_pc_build_component_component_id"),
        "pc_build_component",
        ["component_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pc_build_component_pc_build_id"),
        "pc_build_component",
        ["pc_build_id"],
        unique=False,
    )
    op.create_table(
        "saved_comparison",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("build_a_id", sa.Integer(), nullable=False),
        sa.Column("build_b_id", sa.Integer(), nullable=False),
        sa.Column("workload_profile_id", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["build_a_id"],
            ["pc_build.id"],
            name=op.f("fk_saved_comparison_build_a_id_pc_build"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["build_b_id"],
            ["pc_build.id"],
            name=op.f("fk_saved_comparison_build_b_id_pc_build"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_profile.id"],
            name=op.f("fk_saved_comparison_user_id_user_profile"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workload_profile_id"],
            ["workload_profile.id"],
            name=op.f("fk_saved_comparison_workload_profile_id_workload_profile"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_comparison")),
    )
    op.create_index(
        op.f("ix_saved_comparison_user_id"), "saved_comparison", ["user_id"], unique=False
    )
    op.create_table(
        "analysis_metric_contribution",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_result_id", sa.Integer(), nullable=False),
        sa.Column("component_id", sa.Integer(), nullable=True),
        sa.Column("metric_definition_id", sa.Integer(), nullable=False),
        sa.Column("normalized_score_0_100", sa.Float(), nullable=True),
        sa.Column("weight_applied", sa.Float(), nullable=False),
        sa.Column("weighted_contribution", sa.Float(), nullable=False),
        sa.Column("is_missing_metric", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_result_id"],
            ["analysis_result.id"],
            name=op.f("fk_analysis_metric_contribution_analysis_result_id_analysis_result"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["hardware_component.id"],
            name=op.f("fk_analysis_metric_contribution_component_id_hardware_component"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["metric_definition_id"],
            ["benchmark_metric_definition.id"],
            name=op.f(
                "fk_analysis_metric_contribution_metric_definition_id_benchmark_metric_definition"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_metric_contribution")),
    )
    op.create_index(
        op.f("ix_analysis_metric_contribution_analysis_result_id"),
        "analysis_metric_contribution",
        ["analysis_result_id"],
        unique=False,
    )
    op.create_table(
        "bottleneck_result",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_result_id", sa.Integer(), nullable=False),
        sa.Column("limiting_component_type", sa.String(length=32), nullable=False),
        sa.Column("strongest_component_type", sa.String(length=32), nullable=False),
        sa.Column("spread_points", sa.Float(), nullable=False),
        sa.Column("severity_status", sa.String(length=64), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_result_id"],
            ["analysis_result.id"],
            name=op.f("fk_bottleneck_result_analysis_result_id_analysis_result"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bottleneck_result")),
    )
    op.create_index(
        op.f("ix_bottleneck_result_analysis_result_id"),
        "bottleneck_result",
        ["analysis_result_id"],
        unique=False,
    )
    op.create_table(
        "upgrade_recommendation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_result_id", sa.Integer(), nullable=False),
        sa.Column("priority_order", sa.Integer(), nullable=False),
        sa.Column("component_type", sa.String(length=32), nullable=False),
        sa.Column("affected_metric_key", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("target_score_min", sa.Float(), nullable=False),
        sa.Column("target_score_max", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_result_id"],
            ["analysis_result.id"],
            name=op.f("fk_upgrade_recommendation_analysis_result_id_analysis_result"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_upgrade_recommendation")),
    )
    op.create_index(
        op.f("ix_upgrade_recommendation_analysis_result_id"),
        "upgrade_recommendation",
        ["analysis_result_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_upgrade_recommendation_analysis_result_id"), table_name="upgrade_recommendation"
    )
    op.drop_table("upgrade_recommendation")
    op.drop_index(op.f("ix_bottleneck_result_analysis_result_id"), table_name="bottleneck_result")
    op.drop_table("bottleneck_result")
    op.drop_index(
        op.f("ix_analysis_metric_contribution_analysis_result_id"),
        table_name="analysis_metric_contribution",
    )
    op.drop_table("analysis_metric_contribution")
    op.drop_index(op.f("ix_saved_comparison_user_id"), table_name="saved_comparison")
    op.drop_table("saved_comparison")
    op.drop_index(op.f("ix_pc_build_component_pc_build_id"), table_name="pc_build_component")
    op.drop_index(op.f("ix_pc_build_component_component_id"), table_name="pc_build_component")
    op.drop_table("pc_build_component")
    op.drop_index(op.f("ix_ingestion_run_snapshot_id"), table_name="ingestion_run")
    op.drop_table("ingestion_run")
    op.drop_index("ix_observation_component_metric", table_name="benchmark_observation")
    op.drop_index(op.f("ix_benchmark_observation_source_id"), table_name="benchmark_observation")
    op.drop_index(op.f("ix_benchmark_observation_snapshot_id"), table_name="benchmark_observation")
    op.drop_index(op.f("ix_benchmark_observation_component_id"), table_name="benchmark_observation")
    op.drop_table("benchmark_observation")
    op.drop_index(op.f("ix_analysis_result_share_uuid"), table_name="analysis_result")
    op.drop_index(op.f("ix_analysis_result_pc_build_id"), table_name="analysis_result")
    op.drop_index(op.f("ix_analysis_result_dataset_version"), table_name="analysis_result")
    op.drop_table("analysis_result")
    op.drop_index(op.f("ix_workload_weight_workload_profile_id"), table_name="workload_weight")
    op.drop_table("workload_weight")
    op.drop_index(op.f("ix_raw_dataset_snapshot_source_id"), table_name="raw_dataset_snapshot")
    op.drop_index(
        op.f("ix_raw_dataset_snapshot_dataset_version"), table_name="raw_dataset_snapshot"
    )
    op.drop_table("raw_dataset_snapshot")
    op.drop_index(op.f("ix_pc_build_workload_profile_id"), table_name="pc_build")
    op.drop_index(op.f("ix_pc_build_user_id"), table_name="pc_build")
    op.drop_table("pc_build")
    op.drop_index(op.f("ix_normalized_metric_metric_definition_id"), table_name="normalized_metric")
    op.drop_index(op.f("ix_normalized_metric_dataset_version"), table_name="normalized_metric")
    op.drop_index(op.f("ix_normalized_metric_component_id"), table_name="normalized_metric")
    op.drop_table("normalized_metric")
    op.drop_table("component_specification")
    op.drop_index(op.f("ix_component_alias_component_id"), table_name="component_alias")
    op.drop_index(op.f("ix_component_alias_alias_name"), table_name="component_alias")
    op.drop_table("component_alias")
    op.drop_index(op.f("ix_workload_profile_slug"), table_name="workload_profile")
    op.drop_table("workload_profile")
    op.drop_index(op.f("ix_user_profile_auth_subject"), table_name="user_profile")
    op.drop_table("user_profile")
    op.drop_table("scoring_version")
    op.drop_table("normalization_version")
    op.drop_index(op.f("ix_hardware_component_model_name"), table_name="hardware_component")
    op.drop_index(op.f("ix_hardware_component_component_type"), table_name="hardware_component")
    op.drop_index(op.f("ix_hardware_component_brand"), table_name="hardware_component")
    op.drop_table("hardware_component")
    op.drop_table("benchmark_source")
    op.drop_index(
        op.f("ix_benchmark_metric_definition_subsystem"), table_name="benchmark_metric_definition"
    )
    op.drop_index(
        op.f("ix_benchmark_metric_definition_metric_key"), table_name="benchmark_metric_definition"
    )
    op.drop_table("benchmark_metric_definition")
    op.drop_index(op.f("ix_audit_event_action"), table_name="audit_event")
    op.drop_table("audit_event")
    # ### end Alembic commands ###
